# Generated by Django 3.0.4 on 2020-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seen',
            name='date',
            field=models.DateField(verbose_name='seen date'),
        ),
    ]
